# Use a Python base image
FROM python:3.11

# Set working directory
WORKDIR /backend

# Copy the important contents into the container
COPY requirements.txt .
COPY model ./model
COPY controller ./controller
COPY app.py .
COPY __init__.py .
COPY .env .
COPY wait-for-it.sh .

RUN pip install -r requirements.txt
RUN chmod +x wait-for-it.sh

EXPOSE 8080

CMD ["python", "app.py"]