# Use a Python base image
FROM python:3.11

# Set working directory
WORKDIR /app

# Copy the important contents into the container
COPY requirements.txt .
COPY model ./model
COPY controller ./controller
COPY app.py .

RUN pip install -r requirements.txt

EXPOSE 8080

CMD ["python", "app.py"]